In [1]:
import numpy as np

In [2]:
list = [3,4,6,7,89]

In [3]:
np.array(list)

array([ 3,  4,  6,  7, 89])

In [4]:
np.arange(0,7)

array([0, 1, 2, 3, 4, 5, 6])

In [5]:
np.arange(0,7,3)

array([0, 3, 6])

In [6]:
np.zeros(3,6)

TypeError: data type not understood

In [7]:
np.zeros(3,3)

TypeError: data type not understood

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.identity([4,4])

TypeError: 'list' object cannot be interpreted as an integer

In [15]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
n1 = np.identity(3)+np.identity(3)

In [18]:
print (n1)

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]


In [20]:
np.linspace(0,5,15)

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

In [22]:
np.zeros([3,3,3],int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [23]:
my = np.arange(24)

In [24]:
my

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [25]:
my.reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [26]:
pwd

'/home/prakash'

In [27]:
pwd

'/home/prakash'

In [28]:
pwd

'/home/prakash'