In [1]:
pwd

'/home/prakash/Desktop/Hiteshi-ML-Practice/Data-Preprocessing'

In [2]:
ls

CleanupData.csv  Data-Preprocessing.ipynb


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
data = pd.read_csv('CleanupData.csv')

In [5]:
data

State   Age  Pocket Money Course Purchased
0     Delhi  34.0        7200.0               No
1    Mumbai  17.0        4800.0              Yes
2  Banglore  20.0        5400.0               No
3    Mumbai  28.0        6100.0               No
4  Banglore  30.0           NaN              Yes
5     Delhi  25.0        5800.0              Yes
6    Mumbai   NaN        5200.0               No
7     Delhi  38.0        7900.0              Yes
8  Banglore  40.0        8300.0               No
9     Delhi  27.0        6700.0              Yes

In [6]:
data.head()

State   Age  Pocket Money Course Purchased
0     Delhi  34.0        7200.0               No
1    Mumbai  17.0        4800.0              Yes
2  Banglore  20.0        5400.0               No
3    Mumbai  28.0        6100.0               No
4  Banglore  30.0           NaN              Yes

In [7]:
# get your indept and depnt matrix from dataset
X = data.iloc[:,:-1].values

In [8]:
# matrix of indept variable
X

array([['Delhi', 34.0, 7200.0],
       ['Mumbai', 17.0, 4800.0],
       ['Banglore', 20.0, 5400.0],
       ['Mumbai', 28.0, 6100.0],
       ['Banglore', 30.0, nan],
       ['Delhi', 25.0, 5800.0],
       ['Mumbai', nan, 5200.0],
       ['Delhi', 38.0, 7900.0],
       ['Banglore', 40.0, 8300.0],
       ['Delhi', 27.0, 6700.0]], dtype=object)

In [9]:
# matrix of depnt variable
Y = data.iloc[:,3].values

In [10]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [11]:
data

State   Age  Pocket Money Course Purchased
0     Delhi  34.0        7200.0               No
1    Mumbai  17.0        4800.0              Yes
2  Banglore  20.0        5400.0               No
3    Mumbai  28.0        6100.0               No
4  Banglore  30.0           NaN              Yes
5     Delhi  25.0        5800.0              Yes
6    Mumbai   NaN        5200.0               No
7     Delhi  38.0        7900.0              Yes
8  Banglore  40.0        8300.0               No
9     Delhi  27.0        6700.0              Yes

In [12]:
# how to handle missing values
# Imputation of missing values
from sklearn.preprocessing import Imputer

In [13]:
imputer = Imputer(missing_values='NaN',strategy='mean',axis=0)

In [14]:
imputer.fit(X[:,1:3])

Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)

In [15]:
X[:,1:3] = imputer.transform(X[:,1:3])

In [16]:
X

array([['Delhi', 34.0, 7200.0],
       ['Mumbai', 17.0, 4800.0],
       ['Banglore', 20.0, 5400.0],
       ['Mumbai', 28.0, 6100.0],
       ['Banglore', 30.0, 6377.777777777777],
       ['Delhi', 25.0, 5800.0],
       ['Mumbai', 28.77777777777778, 5200.0],
       ['Delhi', 38.0, 7900.0],
       ['Banglore', 40.0, 8300.0],
       ['Delhi', 27.0, 6700.0]], dtype=object)

In [17]:
# handle categorical data in our data(state-category)
from sklearn.preprocessing import LabelEncoder

In [18]:
labelencoder_X = LabelEncoder()

In [19]:
X[:,0] = labelencoder_X.fit_transform(X[:,0])

In [20]:
X

array([[1, 34.0, 7200.0],
       [2, 17.0, 4800.0],
       [0, 20.0, 5400.0],
       [2, 28.0, 6100.0],
       [0, 30.0, 6377.777777777777],
       [1, 25.0, 5800.0],
       [2, 28.77777777777778, 5200.0],
       [1, 38.0, 7900.0],
       [0, 40.0, 8300.0],
       [1, 27.0, 6700.0]], dtype=object)

In [21]:
# create dummmy matrix for categorical dataset
from sklearn.preprocessing import OneHotEncoder

In [22]:
onehotencoder = OneHotEncoder(categorical_features=[0])
X = onehotencoder.fit_transform(X).toarray()
np.set_printoptions(suppress=True)

In [23]:
X

array([[   0.        ,    1.        ,    0.        ,   34.        ,
        7200.        ],
       [   0.        ,    0.        ,    1.        ,   17.        ,
        4800.        ],
       [   1.        ,    0.        ,    0.        ,   20.        ,
        5400.        ],
       [   0.        ,    0.        ,    1.        ,   28.        ,
        6100.        ],
       [   1.        ,    0.        ,    0.        ,   30.        ,
        6377.77777778],
       [   0.        ,    1.        ,    0.        ,   25.        ,
        5800.        ],
       [   0.        ,    0.        ,    1.        ,   28.77777778,
        5200.        ],
       [   0.        ,    1.        ,    0.        ,   38.        ,
        7900.        ],
       [   1.        ,    0.        ,    0.        ,   40.        ,
        8300.        ],
       [   0.        ,    1.        ,    0.        ,   27.        ,
        6700.        ]])

In [25]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [26]:
# handle Y matrix for categorical data
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)

In [27]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [28]:
# prepare test and training data set
# split our data into 2 parts
# one will be training and other will be testing
from sklearn.cross_validation import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)

In [29]:
X_train

array([[   0.        ,    1.        ,    0.        ,   27.        ,
        6700.        ],
       [   1.        ,    0.        ,    0.        ,   30.        ,
        6377.77777778],
       [   0.        ,    1.        ,    0.        ,   25.        ,
        5800.        ],
       [   0.        ,    0.        ,    1.        ,   28.        ,
        6100.        ],
       [   0.        ,    0.        ,    1.        ,   17.        ,
        4800.        ],
       [   1.        ,    0.        ,    0.        ,   40.        ,
        8300.        ],
       [   0.        ,    1.        ,    0.        ,   34.        ,
        7200.        ],
       [   0.        ,    0.        ,    1.        ,   28.77777778,
        5200.        ]])

In [30]:
Y_train

array([1, 1, 1, 0, 1, 0, 0, 0])

In [31]:
X_test

array([[   1.,    0.,    0.,   20., 5400.],
       [   0.,    1.,    0.,   38., 7900.]])

In [33]:
Y_test

array([0, 1])

In [34]:
# Feature scaling
# Standard deviation or Normalization
from sklearn.preprocessing import StandardScaler

In [35]:
#train dataset use fit_transform
# test dataset use transform
scale_X = StandardScaler()
X_train = scale_X.fit_transform(X_train)
X_test = scale_X.transform(X_test)

In [36]:
X_train

array([[-0.57735027,  1.29099445, -0.77459667, -0.27602759,  0.37370491],
       [ 1.73205081, -0.77459667, -0.77459667,  0.20479466,  0.06516562],
       [-0.57735027,  1.29099445, -0.77459667, -0.59657576, -0.48807723],
       [-0.57735027, -0.77459667,  1.29099445, -0.11575351, -0.20081652],
       [-0.57735027, -0.77459667,  1.29099445, -1.87876845, -1.44561294],
       [ 1.73205081, -0.77459667, -0.77459667,  1.80753552,  1.90576204],
       [-0.57735027,  1.29099445, -0.77459667,  0.84589101,  0.85247276],
       [-0.57735027, -0.77459667,  1.29099445,  0.00890412, -1.06259865]])

In [37]:
X_test

array([[ 1.73205081, -0.77459667, -0.77459667, -1.39794619, -0.87109151],
       [-0.57735027,  1.29099445, -0.77459667,  1.48698735,  1.52274776]])