In [1]:
# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [3]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [4]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [5]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [6]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.
/home/prakash/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/prakash/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/prakash/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/prakash/anaconda3/lib/python3.7/site-packages/t

In [7]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 6, init  = 'uniform',activation = 'relu',input_dim=11))

Instructions for updating:
Colocations handled automatically by placer.


/home/prakash/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """


In [8]:
# Adding the second hidden layer
classifier.add(Dense(output_dim = 6, init  = 'uniform',activation = 'relu'))

/home/prakash/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  


In [9]:
# Adding the output layer
classifier.add(Dense(output_dim=1,init='uniform',activation='sigmoid'))

/home/prakash/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


In [10]:
# Compiling the ANN
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [11]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

Instructions for updating:
Use tf.cast instead.


/home/prakash/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/100
8000/8000 [==============================] - 2s 224us/step - loss: 0.4796 - accuracy: 0.7976
Epoch 2/100
8000/8000 [==============================] - 2s 192us/step - loss: 0.4157 - accuracy: 0.8245
Epoch 3/100
8000/8000 [==============================] - 2s 196us/step - loss: 0.4007 - accuracy: 0.8291
Epoch 4/100
8000/8000 [==============================] - 2s 200us/step - loss: 0.3895 - accuracy: 0.8313
Epoch 5/100
8000/8000 [==============================] - 2s 193us/step - loss: 0.3822 - accuracy: 0.8328
Epoch 6/100
8000/8000 [==============================] - 2s 197us/step - loss: 0.3772 - accuracy: 0.8388
Epoch 7/100
8000/8000 [==============================] - 2s 203us/step - loss: 0.3730 - accuracy: 0.8455
Epoch 8/100
8000/8000 [==============================] - 2s 204us/step - loss: 0.3694 - accuracy: 0.8493
Epoch 9/100
8000/8000 [==============================] - 2s 207us/step - loss: 0.3665 - accuracy: 0.8499
Epoch 10/100
8000/8000 [==============================]

8000/8000 [==============================] - 2s 194us/step - loss: 0.3377 - accuracy: 0.8591
Epoch 79/100
8000/8000 [==============================] - 2s 219us/step - loss: 0.3378 - accuracy: 0.8615
Epoch 80/100
8000/8000 [==============================] - 1s 186us/step - loss: 0.3371 - accuracy: 0.8599
Epoch 81/100
8000/8000 [==============================] - 2s 189us/step - loss: 0.3373 - accuracy: 0.8618
Epoch 82/100
8000/8000 [==============================] - 2s 189us/step - loss: 0.3385 - accuracy: 0.8614
Epoch 83/100
8000/8000 [==============================] - 1s 187us/step - loss: 0.3375 - accuracy: 0.8615
Epoch 84/100
8000/8000 [==============================] - 2s 188us/step - loss: 0.3378 - accuracy: 0.8608
Epoch 85/100
8000/8000 [==============================] - 2s 211us/step - loss: 0.3376 - accuracy: 0.8606
Epoch 86/100
8000/8000 [==============================] - 2s 223us/step - loss: 0.3383 - accuracy: 0.8614
Epoch 87/100
8000/8000 [==============================] - 2

In [12]:
# Part 3 - Making the predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [13]:
cm

array([[1486,  109],
       [ 180,  225]])

In [14]:
1486+225

1711

In [16]:
1711/20

85.55

In [17]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])